version: '2'
services:
    ajc-app:
        image: ajc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://ajc-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ajc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ajc-mongodb:
        extends:
            file: mongodb.yml
            service: ajc-mongodb
